### ISSUE TITLE
Remove configmap for Nginx

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram-helm#7]
This was added while testing configurations for allowing headers with underscores, but I think a the end it's having no effect on the controllers.

For reference: on the 

`nginx-ingress-ingress-nginx-controller-9cf778db5-h27tg .yaml`
```

  containers:
    - name: controller
      image: >-
        k8s.gcr.io/ingress-nginx/controller:v0.44.0@sha256:3dd0fac48073beaca2d67a78c746c7593f9c575168a17139a9955a82c63c4b9a
      args:
        - /nginx-ingress-controller
        - >-
          --publish-service=$(POD_NAMESPACE)/nginx-ingress-ingress-nginx-controller
        - '--election-id=ingress-controller-leader'
        - '--ingress-class=nginx'
        - '--configmap=$(POD_NAMESPACE)/nginx-ingress-ingress-nginx-controller'
        - '--validating-webhook=:8443'
        - '--validating-webhook-certificate=/usr/local/certificates/cert'
        - '--validating-webhook-key=/usr/local/certificates/key'
```
Notice the configmap name is `nginx-ingress-ingress-nginx-controller`. I think the configmaps was named incorrectly from the beggining
